"""empty message

Revision ID: 806e62162dd5
Revises: 53e6d331a310
Create Date: 2023-10-12 17:03:58.792221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806e62162dd5'
down_revision = '53e6d331a310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('c0', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('c0')

    # ### end Alembic commands ###
