"""mix users from phase 1 with phase 2

Revision ID: 8cee2deca324
Revises: fdd1c97a3442
Create Date: 2024-03-20 14:58:44.813320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cee2deca324'
down_revision = 'fdd1c97a3442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prod1', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('prod2', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('prod3', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('prod4', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('prod5', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('prod5')
        batch_op.drop_column('prod4')
        batch_op.drop_column('prod3')
        batch_op.drop_column('prod2')
        batch_op.drop_column('prod1')

    # ### end Alembic commands ###
