"""products table

Revision ID: fb7eacc3f1a7
Revises: 4a1d7097c185
Create Date: 2023-10-05 12:39:57.812547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7eacc3f1a7'
down_revision = '4a1d7097c185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('c1', sa.String(length=100), nullable=True),
    sa.Column('c2', sa.String(length=100), nullable=True),
    sa.Column('c3', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
